### ISSUE TITLE
2.1.6 Milestone

### ISSUE THREAD

**Issue by miry** [Shopify/toxiproxy#315]
## 2.1.6

[Query](https://github.com/Shopify/toxiproxy/issues?q=created%3A%3E2021-09-01+)

- [x] Consistent code style with linting
  - [x] Run linters on PRs
  - [x] Limit the max line size
  - [x] Remove the unused code lines
  - [x] Function length
- [x] Docker image use scratch base image
- [x] Support toxiproxy url via env variables

## Post release
- [ ] Notify @maaslalani

**Comment by miry** [comment]
Released in https://github.com/Shopify/toxiproxy/actions/runs/1265809235
