### ISSUE TITLE
2.3.0 Milestone

### ISSUE THREAD

**Issue by miry** [Shopify/toxiproxy#337]
# 2.3.0

[Query](https://github.com/Shopify/toxiproxy/issues?q=created%3A%3E2021-10-17+)

## Tasks

- Make a structured project folders
  - [x] https://github.com/Shopify/toxiproxy/pull/336/ 
  - [x] https://github.com/Shopify/toxiproxy/pull/335
- Dependencies
  - [x] https://github.com/Shopify/toxiproxy/pull/334
- [x] https://github.com/Shopify/toxiproxy/pull/338
- [x] https://github.com/Shopify/toxiproxy/pull/291
- [x] https://github.com/Shopify/toxiproxy/pull/339
- [x] https://github.com/Shopify/toxiproxy/issues/343

## Post release

- [x] Notify ...
- [x] Update homebrew: https://github.com/Shopify/homebrew-shopify/pull/331

**Comment by miry** [comment]
Released: https://github.com/Shopify/toxiproxy/releases/tag/v2.3.0
