### ISSUE TITLE
2.4.0 Milestone

### ISSUE THREAD

**Issue by miry** [Shopify/toxiproxy#350]
# 2.4.0

[Query](https://github.com/Shopify/toxiproxy/issues?q=created%3A%3E2022-12-24+)
[Milestone](https://github.com/Shopify/toxiproxy/milestone/6)

## Tasks

Main features
- [ ] https://github.com/Shopify/toxiproxy/pull/347
- [ ] https://github.com/Shopify/toxiproxy/issues/79
- [ ] https://github.com/Shopify/toxiproxy/pull/211
- [ ] https://github.com/Shopify/toxiproxy/pull/132
- [ ] https://github.com/Shopify/toxiproxy/pull/134

Small tweaks / improvements
- [ ] https://github.com/Shopify/toxiproxy/issues/341
- [ ] https://github.com/Shopify/toxiproxy/issues/348

## Post release

- [ ] Notify ...
- [ ] Update homebrew: https://github.com/Shopify/homebrew-shopify/pull/331
