### ISSUE TITLE
2.5.0 Milestone

### ISSUE THREAD

**Issue by miry** [Shopify/toxiproxy#367]
# 2.5.0

[Query](https://github.com/Shopify/toxiproxy/issues?q=created%3A%3E2022-03-03+)
[Milestone](https://github.com/Shopify/toxiproxy/milestone/8)

## Tasks

Main features

Small tweaks / improvements
- [x] https://github.com/Shopify/toxiproxy/issues/254
- [x] https://github.com/Shopify/toxiproxy/pull/368
- [x] https://github.com/Shopify/toxiproxy/pull/415
- [x] https://github.com/Shopify/toxiproxy/pull/413
- [x] https://github.com/Shopify/toxiproxy/pull/416
- [x] https://github.com/Shopify/toxiproxy/pull/418
- [x] https://github.com/Shopify/toxiproxy/pull/422
- [x] https://github.com/Shopify/toxiproxy/pull/421
- [x] https://github.com/Shopify/toxiproxy/pull/423
- [x] https://github.com/Shopify/toxiproxy/pull/425
- [x] https://github.com/Shopify/toxiproxy/pull/430
- [x] https://github.com/Shopify/toxiproxy/pull/431
- [x] https://github.com/Shopify/toxiproxy/pull/432
- [x] https://github.com/Shopify/toxiproxy/pull/433
- [x] https://github.com/Shopify/toxiproxy/pull/437
- [x] https://github.com/Shopify/toxiproxy/pull/438

## Post release

- [x] Notify ...
- [x] Update homebrew: https://github.com/Shopify/homebrew-shopify/pull/331
