### ISSUE TITLE
2.6.0 Milestone

### ISSUE THREAD

**Issue by miry** [Shopify/toxiproxy#434]
# 2.6.0

[Query](https://github.com/Shopify/toxiproxy/issues?q=created%3A%3E2022-03-03+)
[Milestone](https://github.com/Shopify/toxiproxy/milestone/9)

## Tasks

Main features
- [ ] [Toxics are not set when creating a proxy for the first time.](https://github.com/Shopify/toxiproxy/issues/79)
- [ ] [Populate toxics at startup from a json string](https://github.com/Shopify/toxiproxy/pull/211)
- [ ] [Add Bidirectional Toxics](https://github.com/Shopify/toxiproxy/pull/132)
- [ ] [Update ChanReader / ChanWriter for use inside toxics](https://github.com/Shopify/toxiproxy/pull/134)

Small tweaks / improvements
- [ ] https://github.com/Shopify/toxiproxy/pull/341
- [ ] https://github.com/Shopify/toxiproxy/issues/414
- [ ] https://github.com/Shopify/toxiproxy/issues/419
- [x] https://github.com/Shopify/toxiproxy/issues/420
- [x] https://github.com/Shopify/toxiproxy/pull/439
- [x] https://github.com/Shopify/toxiproxy/pull/441
- [x] https://github.com/Shopify/toxiproxy/pull/445

## Post release

- [ ] Notify ...
- [ ] Update homebrew: https://github.com/Shopify/homebrew-shopify/pull/331
